Repository AY2425S1-CS2103T-T11-3/tp, pull requests merged in 2024-11, with the labels that each got.

#172 Bug fixes
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/ui/suggestion/Commands.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
Labels: alpha-bug

#173 More bug fixes
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddwCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewwCommand.java
  src/main/java/seedu/address/ui/suggestion/Commands.java
Labels: alpha-bug

#171 Bug fix2
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditwCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/model/person/NameMatchesKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/EditwCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
Labels: alpha-bug

#177 Deletew command
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeletewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/suggestion/Commands.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletewCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#178 More bug fixes again
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewwCommand.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/wedding/PersonHasWeddingPredicate.java
  src/main/java/seedu/address/ui/WeddingCard.java
  src/main/java/seedu/address/ui/suggestion/Commands.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewwCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/wedding/PersonHasWeddingPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#186 Alpha bug fixing
  src/main/java/seedu/address/logic/commands/AddwCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditwCommand.java
  src/main/java/seedu/address/logic/parser/ViewwCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/wedding/Wedding.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/WeddingCard.java
  src/main/java/seedu/address/ui/suggestion/Commands.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddwCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/ModelStubAcceptingWeddingAdded.java
Labels: alpha-bug

#188 Fix issue #125
  src/main/java/seedu/address/logic/commands/AddwCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeletewCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewwCommand.java
  src/main/java/seedu/address/ui/suggestion/Commands.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: alpha-bug

#189 New User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/WeddingClassDiagram.puml
  docs/images/UI.png
  docs/images/Ui.png
  docs/images/addw_example.png
  docs/images/error_example_assign.png
  docs/images/multi_filter_weddings_unfiltered.png
  docs/images/multiple_match.png
  docs/images/multiple_match_solution.png
  docs/images/success_multi_match.png
  docs/images/view_mulitple_weddings_unfiltered.png
Labels: Enhancement

#194 fix suggestion indent issue
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/DarkTheme.css
Labels: Enhancement

#294 [can review] Ped bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: bug.documentation
